# 驱动配置信息
debug: false # Enable debug logs.
trace: false # Enable trace logs.

## include other yml config.
spring.profiles:
  # Comma-separated list of active profiles. Can be overridden by a command line switch.
  active:
    - dev
#  # Unconditionally activate the specified comma-separated list of profiles (or list of profiles if using YAML).
#  include:
#    - dev
#    - release

# 服务发现配置
discovery: &discovery
  # provider: local/dns/etcd/consul/zookeeper
  # provider 会自动识别
  # fixme 该模式无法复用配置，因为每次都是变更的，这里只是作为 examples 写在这里
  local:
    - 127.0.0.1:3001
    - 127.0.0.1:3002
  dns:
    - 127.0.0.1:5001
    - 127.0.0.1:5003
  etcd:
    endpoints:
      - 127.0.0.1:6000
      - 127.0.0.1:6001
  consul:
    agent: 127.0.0.1:7001
  zookeeper:
    - 127.0.0.1:7100

# grpc server 配置
grpcs:
  # server 配置
  serverConfig: &nettyServer
    nettyConfig:
      maxInboundSize: 1024
#    nettySharedConfig:
#      xx: 1

  # 默认支持的两个服务，该模式可以自动使用注解
  ram:
    # 给特定 server 启用
    - primary
  # 特定 server 启用 session
  session:
    - primary

  servers:
    # 内置 primary
    - scopeName: primary
      address: 127.0.0.1:8081
      enableHealthStatus: false
      <<: *nettyServer

    # 内置 private
    - scopeName: private
      address: 0.0.0.0:8080
      enableHealthStatus: true
      <<: *nettyServer
      # 注册发现配置
      discovery:
        # 该值如果不设置 则 使用 默认配置
        serviceName: examplesPrivateService
        <<: *discovery

    # 自定义地址1
    - scopeName: mixed1
      address: 127.0.0.1:8079
      enableHealthStatus: true
      <<: *nettyServer
      # 注册发现配置
      discovery:
        # 该值如果不设置 则 使用 默认配置
        serviceName: examplesMixed1Service
        <<: *discovery

grpc:

  # grpc client 配置
  clientConfig: &nettyClient
    nettyConfig:
      maxInboundSize: 1024
    nettySharedConfig:

  client: &client
    <<: *nettyClient
    # 从远程 注册发现中心 发现配置
    discovery:
      <<: *discovery

  clients:
    # 以下配置写法会从远程 service 读取到 远程注册到 注册发现 组件的 service address
    # 该 scopeName 则是使用本地的 scopeName 对应的 拦截器等等
    # scopeName 保持唯一
    - serviceName: examplesServiceRpc
      <<: *nettyClient
      # 从远程 注册发现中心 发现配置
      discovery:
        local:
          - 127.0.0.1:9001
          - 127.0.0.1:9002

    # 该 配置会使用 本地定义的 mixed1 的拦截器 等等配置
    - serviceName: examplesService1Rpc
      <<: *client
