# https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/htmlsingle/#common-application-properties
# 配置文件统一先读环境变量，其次才是默认配置
# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
debug: ${X-DEBUG:false} # Enable debug logs.
trace: ${X-TRACE:false} # Enable trace logs.

server.port: 8000

## include other yml config.
spring.profiles:
  # Comma-separated list of active profiles. Can be overridden by a command line switch.
  active:
  # Unconditionally activate the specified comma-separated list of profiles (or list of profiles if using YAML).
  include:
    - uc

spring.jpa.hibernate:
  #    ddl-auto: create-drop
  ddl-auto: update
  generate-ddl: false