version: "3"
services:

  # https://www.jianshu.com/p/4d86e9c33e0d

  #  # 登录
  platform-passport:
    image: platform/passport4flux
    restart: always
    ports:
      # 外网端口 - docker 容器内端口
      - "0.0.0.0:9001:8888"
    links:
      - mongodb-node0

  # mongodb 节点0配置
  mongodb-node0:
    image: mongo:3.2.18
    restart: always
    ports:
      # 外部访问端口 27017
      - "127.0.0.1:27017:27017"
    # 挂着宿主机文件到 容器 内，持久化数据
    volumes:
      - ./mongodb:/data/db
      - ./mongodb/keyfile:/opt/keyfile